name: overparameterization
channels:
  - defaults
  - conda-forge
  - anaconda-fusion
  - pytorch
dependencies:
  - python=3.6.2
  - pip=9.0.1
  - wheel=0.33.4

  - pytest=5.0.1
  - notebook=6.0.1
  - pandas=1.0.0
  - seaborn=0.10.0

  - blas
  - numpy=1.16.2
  - matplotlib=3.0.3

  - cudatoolkit=10.0
  - torchvision=0.4.0
  - pytorch=1.3.0
  
  - pip:
    - Pillow==6.2.2
